So far, you have written some test sentences and generated a word index and then created sequences for the sentences.

Now you will tokenize and sequence a larger body of text, specifically reviews from Amazon and Yelp.

# About the dataset
You will use a dataset containing Amazon and Yelp reviews of products and restaurants. This dataset was originally extracted from Kaggle.

The dataset includes reviews, and each review is labelled as 0 (bad) or 1 (good). However, in this exercise, you will only work with the reviews, not the labels, to practice tokenizing and sequencing the text.

Example good reviews:
This is hands down the best phone I've ever had.
Four stars for the food & the guy in the blue shirt for his great vibe & still letting us in to eat !
Example bad reviews:
A lady at the table next to us found a live green caterpillar In her salad
If you plan to use this in a car forget about it.
See more reviews
Feel free to download the dataset from a drive folder belonging to Udacity and open it on your local machine to see more reviews.

In [1]:
import tensorflow as tf
import numpy as np 
import pandas as pd
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer

# Get the corpus of text
The combined dataset of reviews has been saved in a Google drive belonging to Udacity. You can download it from there.

In [2]:
#path = tf.keras.utils.get_file('reviews.csv', 'https://drive.google.com/uc?id=13ySLC_ue6Umt9RJYSeM2t-V0kCv-4C-P')
#print (path)

IndentationError: unexpected indent (<ipython-input-2-6e90fed5d476>, line 2)

# Get the dataset
Each row in the csv file is a separate review.

The csv file has 2 columns:

text (the review)
sentiment (0 or 1 indicating a bad or good review)

In [4]:
dataset = pd.read_csv("combined_data.csv")

dataset.head()

Unnamed: 0                                               text  sentiment
0           0  So there is no way for me to plug it in here i...          0
1           1                         Good case Excellent value.          1
2           2                             Great for the jawbone.          1
3           3  Tied to charger for conversations lasting more...          0
4           4                                  The mic is great.          1

# Get the reviews from the csv file

In [5]:
dataset.columns

Index(['Unnamed: 0', 'text', 'sentiment'], dtype='object')

In [12]:
reviews = dataset['text'].to_list()
print(reviews[1:10])

['Good case Excellent value.', 'Great for the jawbone.', 'Tied to charger for conversations lasting more than 45 minutes.MAJOR PROBLEMS!!', 'The mic is great.', 'I have to jiggle the plug to get it to line up right to get decent volume.', 'If you have several dozen or several hundred contacts then imagine the fun of sending each of them one by one.', 'If you are Razr owner...you must have this!', 'Needless to say I wasted my money.', 'What a waste of money and time!.']


# Tokenize the text
Create the tokenizer, specify the OOV token, tokenize the text, then inspect the word index.

In [15]:
tokenize = Tokenizer(oov_token="<OOV>")
tokenize.fit_on_texts(reviews)

In [29]:
word_index = tokenize.word_index
print(len(word_index))

3261


# Generate sequences for the reviews
Generate a sequence for each review. Set the max length to match the longest review. Add the padding zeros at the end of the review for reviews that are not as long as the longest one.

In [31]:
seq = tokenize.texts_to_sequences(reviews)
pad_seq = tf.keras.preprocessing.sequence.pad_sequences(seq)
print(pad_seq)

[[   0    0    0 ...  113    5 1429]
 [   0    0    0 ...  110   87  397]
 [   0    0    0 ...   13    2  732]
 ...
 [   0    0    0 ...   12   60   40]
 [   0    0    0 ...  246  243   39]
 [   0    0    0 ...  605    2  375]]


In [33]:
# What is the shape of the vector containing the padded sequences?
# The shape shows the number of sequences and the length of each one.
print("The Shape of Padded Sequence is: ",pad_seq.shape)

print("The First Review: ",reviews[0])

print("The padded seq of the first review: ",pad_seq[0])

The Shape of Padded Sequence is:  (1992, 139)
The First Review:  So there is no way for me to plug it in here in the US unless I go by a converter.
The padded seq of the first review:  [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0   28   59    8   56  142   13   61    7
  269    6   15   46   15    2  149  449    4   60  113    5 1429]
